# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

ru-main:
    - label: Проект
      title: Проект
      path: ru/ru-project
    - label: Расположение
      title: Расположение
      path: ru/ru-location
    - label: Инфраструктура
      title: Инфраструктура
      path: ru/ru-info
    - label: Планировки
      title: Планировки
      path: ru/ru-plans
    - label: Галерея
      title: Галерея
      path: ru/ru-gallery
    - label: Латвия
      title: Латвия
      path: ru/ru-latvia
    - label: Контакты
      title: Контакты
      path: ru/ru-contacts

lv-main:
    - label: Проект
      title: Проект
      path: lv/lv-project
    - label: Расположение
      title: Расположение
      path: lv/lv-location
    - label: Инфраструктура
      title: Инфраструктура
      path: lv/lv-info
    - label: Планировки
      title: Планировки
      path: lv/lv-plans
    - label: Галерея
      title: Галерея
      path: lv/lv-gallery
    - label: Латвия
      title: Латвия
      path: lv/lv-latvia
    - label: Контакты
      title: Контакты
      path: lv/lv-contacts

en-main:
    - label: Проект
      title: Проект
      path: en/en-project
    - label: Расположение
      title: Расположение
      path: en/en-location
    - label: Инфраструктура
      title: Инфраструктура
      path: en/en-info
    - label: Планировки
      title: Планировки
      path: en/en-plans
    - label: Галерея
      title: Галерея
      path: en/en-gallery
    - label: Латвия
      title: Латвия
      path: en/en-latvia
    - label: Контакты
      title: Контакты
      path: en/en-contacts